name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Generate timestamp tag
        id: vars
        run: echo "TAG=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        run: |
          gcloud builds submit \
          --tag "${{ vars.ARTIFACT_URL }}:${{ steps.vars.outputs.TAG }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${{ vars.CLOUDRUN_SERVICE_NAME }}" \
          --image "${{ vars.ARTIFACT_URL }}:${{ steps.vars.outputs.TAG }}" \
          --region "${{ vars.GCP_REGION }}" \
          --project "${{ vars.GCP_PROJECT_ID }}" \
          --allow-unauthenticated

      - name: Output version deployed
        run: echo "Deployed version:${{ steps.vars.outputs.TAG }}"

      
      
