name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Generate timestamp tag
        id: image
        run: echo "TAG=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Debug image name
        run: echo "Image:${{ secrets.ARTIFACT_URL }}:${{ steps.image.outputs.TAG }}"

      - name: Build and Push Image
        working-directory: ./backend
        run: |
          gcloud builds submit . \
            --tag "${{ secrets.ARTIFACT_URL }}:${{ steps.image.outputs.TAG }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${{ secrets.CLOUDRUN_SERVICE_NAME }}" \
            --image "${{ secrets.ARTIFACT_URL }}:${{ steps.image.outputs.TAG }}" \
            --region "${{ secrets.GCP_REGION }}" \
            --project "${{ secrets.GCP_PROJECT_ID }}" \
            --allow-unauthenticated

      - name: Output version deployed
        run: echo "Deployed version:${{ steps.image.outputs.TAG }}"
